# Generated by Django 5.1.4 on 2024-12-15 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('schedule', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('video_url', models.URLField(blank=True, help_text='URL video pembelajaran (contoh: YouTube)', null=True)),
                ('pdf_material', models.FileField(blank=True, help_text='Unggah materi dalam format PDF', null=True, upload_to='materials/')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='profile_pics')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('about', models.TextField(blank=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=10)),
                ('courses', models.ManyToManyField(blank=True, related_name='enrolled_users', to='cd_app.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('status', models.CharField(choices=[('Belum Presensi', 'Belum Presensi'), ('Presensi telah dilakukan', 'Presensi telah dilakukan')], max_length=50)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cd_app.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cd_app.userprofileinfo')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_courses', to='cd_app.userprofileinfo'),
        ),
    ]
