# Generated by Django 5.1.4 on 2024-12-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd_app', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='announcement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
