# Generated by Django 5.1.3 on 2024-11-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cd_app', '0002_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
